apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: arc-store-ingress
  namespace: arc-store
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - http:
        paths:
          - path: /api/
            pathType: Prefix
            backend:
              service:
                name: arc-backend
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: arc-frontend
                port:
                  number: 80
