#!/usr/bin/env python3
import json
import os
import re
import sys
from pathlib import Path

import requests


DEFAULT_MODEL = "claude-3-7-sonnet-latest"
ANTHROPIC_API_URL = "https://api.anthropic.com/v1/messages"


def _stderr(msg):
    print(msg, file=sys.stderr)


def _read_prompt(prompt_file):
    path = Path(prompt_file)
    if not path.exists():
        raise FileNotFoundError(f"Prompt file not found: {prompt_file}")
    return path.read_text(encoding="utf-8")


def _extract_json(text):
    text = text.strip()
    if not text:
        raise ValueError("Empty model output")

    try:
        return json.loads(text)
    except json.JSONDecodeError:
        pass

    fenced = re.search(r"```(?:json)?\s*(\{[\s\S]*\})\s*```", text)
    if fenced:
        return json.loads(fenced.group(1))

    brace = re.search(r"(\{[\s\S]*\})", text)
    if brace:
        return json.loads(brace.group(1))

    raise ValueError("Could not find JSON object in model output")


def _fallback_result(reason):
    return {
        "root_cause": f"Claude runner fallback: {reason}",
        "confidence": 0.0,
        "proposed_changes": [
            "No patch generated by claude_runner fallback.",
            "Check ANTHROPIC_API_KEY and CLAUDE_MODEL configuration.",
        ],
        "patch_style": "claude-runner-fallback",
    }


def _call_anthropic(prompt_text):
    api_key = os.getenv("ANTHROPIC_API_KEY", "").strip()
    if not api_key:
        return _fallback_result("ANTHROPIC_API_KEY is not set")

    model = os.getenv("CLAUDE_MODEL", DEFAULT_MODEL)
    max_tokens = int(os.getenv("CLAUDE_MAX_TOKENS", "2200"))

    system_msg = (
        "You are an issue investigation agent. Return only valid JSON object output. "
        "Do not include markdown or prose outside JSON."
    )

    user_msg = (
        "Use the following prompt instructions exactly and produce one JSON object result:\n\n"
        f"{prompt_text}"
    )

    payload = {
        "model": model,
        "max_tokens": max_tokens,
        "system": system_msg,
        "messages": [
            {"role": "user", "content": user_msg},
        ],
    }

    headers = {
        "x-api-key": api_key,
        "anthropic-version": "2023-06-01",
        "content-type": "application/json",
    }

    response = requests.post(ANTHROPIC_API_URL, headers=headers, json=payload, timeout=120)
    if response.status_code >= 300:
        return _fallback_result(f"Anthropic API error {response.status_code}: {response.text[:300]}")

    body = response.json()
    chunks = body.get("content", [])
    text_chunks = [chunk.get("text", "") for chunk in chunks if chunk.get("type") == "text"]
    raw_text = "\n".join(text_chunks).strip()

    try:
        parsed = _extract_json(raw_text)
    except Exception as err:  # noqa: BLE001
        return _fallback_result(f"Could not parse Claude output as JSON: {err}")

    if not isinstance(parsed, dict):
        return _fallback_result("Claude output JSON was not an object")

    return parsed


def main():
    if len(sys.argv) < 2:
        print(json.dumps(_fallback_result("Usage: python agent/claude_runner.py <prompt_file>")))
        return 0

    prompt_file = sys.argv[1]
    try:
        prompt_text = _read_prompt(prompt_file)
        result = _call_anthropic(prompt_text)
    except Exception as err:  # noqa: BLE001
        _stderr(f"claude_runner error: {err}")
        result = _fallback_result(str(err))

    print(json.dumps(result))
    return 0


if __name__ == "__main__":
    sys.exit(main())
